package utils

// LicensorYAML is specific filename which would be searched to get license
const LicensorYAML = "licensor.yml"

// UniqueIdentifier is header in comment
const UniqueIdentifier = "License generated by licensor(https://github.com/Marvin9/licensor)."

// flags
const (
	// PROJECT: -project [projectDir]
	PROJECT = "-project"
	// EXT: -ext [extensions...] :For example -ext go cpp js
	EXT = "-ext"
	// LICENSE: -license [license file path/url] :For example -license "./templateLicense.txt"
	LICENSE = "-license"
	// IGNORE: -ignore [files...]
	IGNORE = "-ignore"
	// TEMPLATE: -template [json string] :For example -template "{\"name\":\"mayur\"}"
	TEMPLATE = "-template"
	// REMOVE: -remove
	REMOVE = "-remove"
)

// Commands - valid commands
var Commands = []string{
	PROJECT, EXT, LICENSE, IGNORE, TEMPLATE, REMOVE,
}

// SupportedFileExtensions - files which we can inject comment (From our side)
// Each may have different multiline comment syntax
var SupportedFileExtensions = []string{
	"go", "c", "cpp", "js", "css",
}
